# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/sysclassfiles/cpu_1/cpu_1/cpu_1.srcs/sources_1/ip/ram3/ram3.xci
# IP: The module: 'ram3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/sysclassfiles/cpu_1/cpu_1/cpu_1.srcs/sources_1/ip/ram3/ram3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/sysclassfiles/cpu_1/cpu_1/cpu_1.srcs/sources_1/ip/ram3/ram3.xci
# IP: The module: 'ram3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/sysclassfiles/cpu_1/cpu_1/cpu_1.srcs/sources_1/ip/ram3/ram3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
